// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/medical_record_creator.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/orvosi/api/entity"
)

// MockMedicalRecordInserter is a mock of MedicalRecordInserter interface
type MockMedicalRecordInserter struct {
	ctrl     *gomock.Controller
	recorder *MockMedicalRecordInserterMockRecorder
}

// MockMedicalRecordInserterMockRecorder is the mock recorder for MockMedicalRecordInserter
type MockMedicalRecordInserterMockRecorder struct {
	mock *MockMedicalRecordInserter
}

// NewMockMedicalRecordInserter creates a new mock instance
func NewMockMedicalRecordInserter(ctrl *gomock.Controller) *MockMedicalRecordInserter {
	mock := &MockMedicalRecordInserter{ctrl: ctrl}
	mock.recorder = &MockMedicalRecordInserterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMedicalRecordInserter) EXPECT() *MockMedicalRecordInserterMockRecorder {
	return m.recorder
}

// Insert mocks base method
func (m *MockMedicalRecordInserter) Insert(ctx context.Context, record *entity.MedicalRecord) *entity.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, record)
	ret0, _ := ret[0].(*entity.Error)
	return ret0
}

// Insert indicates an expected call of Insert
func (mr *MockMedicalRecordInserterMockRecorder) Insert(ctx, record interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockMedicalRecordInserter)(nil).Insert), ctx, record)
}
